/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@ZiqniTechGatewayApiClient);
  }
}(this, function(expect, @ZiqniTechGatewayApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @ZiqniTechGatewayApiClient.MemberAchievement();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MemberAchievement', function() {
    it('should create an instance of MemberAchievement', function() {
      // uncomment below and update the code to test MemberAchievement
      //var instance = new @ZiqniTechGatewayApiClient.MemberAchievement();
      //expect(instance).to.be.a(@ZiqniTechGatewayApiClient.MemberAchievement);
    });

    it('should have the property memberId (base name: "memberId")', function() {
      // uncomment below and update the code to test the property memberId
      //var instance = new @ZiqniTechGatewayApiClient.MemberAchievement();
      //expect(instance).to.be();
    });

    it('should have the property achievementId (base name: "achievementId")', function() {
      // uncomment below and update the code to test the property achievementId
      //var instance = new @ZiqniTechGatewayApiClient.MemberAchievement();
      //expect(instance).to.be();
    });

    it('should have the property goalPercentageComplete (base name: "goalPercentageComplete")', function() {
      // uncomment below and update the code to test the property goalPercentageComplete
      //var instance = new @ZiqniTechGatewayApiClient.MemberAchievement();
      //expect(instance).to.be();
    });

    it('should have the property issued (base name: "issued")', function() {
      // uncomment below and update the code to test the property issued
      //var instance = new @ZiqniTechGatewayApiClient.MemberAchievement();
      //expect(instance).to.be();
    });

  });

}));
