/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@ZiqniTechGatewayApiClient);
  }
}(this, function(expect, @ZiqniTechGatewayApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SseMemberMessage', function() {
    it('should create an instance of SseMemberMessage', function() {
      // uncomment below and update the code to test SseMemberMessage
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be.a(@ZiqniTechGatewayApiClient.SseMemberMessage);
    });

    it('should have the property nodeId (base name: "nodeId")', function() {
      // uncomment below and update the code to test the property nodeId
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

    it('should have the property accountId (base name: "accountId")', function() {
      // uncomment below and update the code to test the property accountId
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

    it('should have the property entityId (base name: "entityId")', function() {
      // uncomment below and update the code to test the property entityId
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

    it('should have the property messageType (base name: "messageType")', function() {
      // uncomment below and update the code to test the property messageType
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

    it('should have the property memberId (base name: "memberId")', function() {
      // uncomment below and update the code to test the property memberId
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

    it('should have the property parentEntityId (base name: "parentEntityId")', function() {
      // uncomment below and update the code to test the property parentEntityId
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

    it('should have the property rank (base name: "rank")', function() {
      // uncomment below and update the code to test the property rank
      //var instance = new @ZiqniTechGatewayApiClient.SseMemberMessage();
      //expect(instance).to.be();
    });

  });

}));
