/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@ZiqniTechGatewayApiClient);
  }
}(this, function(expect, @ZiqniTechGatewayApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @ZiqniTechGatewayApiClient.Widget();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Widget', function() {
    it('should create an instance of Widget', function() {
      // uncomment below and update the code to test Widget
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be.a(@ZiqniTechGatewayApiClient.Widget);
    });

    it('should have the property jsonClass (base name: "jsonClass")', function() {
      // uncomment below and update the code to test the property jsonClass
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property accountId (base name: "accountId")', function() {
      // uncomment below and update the code to test the property accountId
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property referenceIdList (base name: "referenceIdList")', function() {
      // uncomment below and update the code to test the property referenceIdList
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property themeName (base name: "themeName")', function() {
      // uncomment below and update the code to test the property themeName
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property widgetType (base name: "widgetType")', function() {
      // uncomment below and update the code to test the property widgetType
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property includeDependencies (base name: "includeDependencies")', function() {
      // uncomment below and update the code to test the property includeDependencies
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property deprecated (base name: "deprecated")', function() {
      // uncomment below and update the code to test the property deprecated
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new @ZiqniTechGatewayApiClient.Widget();
      //expect(instance).to.be();
    });

  });

}));
