/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AchievementAggregations from './AchievementAggregations';
import Error from './Error';
import ResponseMeta from './ResponseMeta';

/**
 * The AchievementIssuedResponse model module.
 * @module model/AchievementIssuedResponse
 * @version 0.0.1
 */
class AchievementIssuedResponse {
    /**
     * Constructs a new <code>AchievementIssuedResponse</code>.
     * @alias module:model/AchievementIssuedResponse
     */
    constructor() { 
        
        AchievementIssuedResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AchievementIssuedResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AchievementIssuedResponse} obj Optional instance to populate.
     * @return {module:model/AchievementIssuedResponse} The populated <code>AchievementIssuedResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AchievementIssuedResponse();

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ResponseMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('aggregations')) {
                obj['aggregations'] = ApiClient.convertToType(data['aggregations'], [AchievementAggregations]);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ResponseMeta} meta
 */
AchievementIssuedResponse.prototype['meta'] = undefined;

/**
 * @member {Array.<module:model/AchievementAggregations>} aggregations
 */
AchievementIssuedResponse.prototype['aggregations'] = undefined;

/**
 * @member {Array.<module:model/Error>} errors
 */
AchievementIssuedResponse.prototype['errors'] = undefined;






export default AchievementIssuedResponse;

