/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Achievement from './Achievement';
import Error from './Error';

/**
 * The AchievementByIdResponse model module.
 * @module model/AchievementByIdResponse
 * @version 0.0.1
 */
class AchievementByIdResponse {
    /**
     * Constructs a new <code>AchievementByIdResponse</code>.
     * @alias module:model/AchievementByIdResponse
     */
    constructor() { 
        
        AchievementByIdResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AchievementByIdResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AchievementByIdResponse} obj Optional instance to populate.
     * @return {module:model/AchievementByIdResponse} The populated <code>AchievementByIdResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AchievementByIdResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = Achievement.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Achievement} data
 */
AchievementByIdResponse.prototype['data'] = undefined;

/**
 * @member {Array.<module:model/Error>} errors
 */
AchievementByIdResponse.prototype['errors'] = undefined;






export default AchievementByIdResponse;

