/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AchievementIssuedCount from './AchievementIssuedCount';

/**
 * The AchievementAggregations model module.
 * @module model/AchievementAggregations
 * @version 0.0.1
 */
class AchievementAggregations {
    /**
     * Constructs a new <code>AchievementAggregations</code>.
     * @alias module:model/AchievementAggregations
     */
    constructor() { 
        
        AchievementAggregations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AchievementAggregations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AchievementAggregations} obj Optional instance to populate.
     * @return {module:model/AchievementAggregations} The populated <code>AchievementAggregations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AchievementAggregations();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [AchievementIssuedCount]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/AchievementIssuedCount>} items
 */
AchievementAggregations.prototype['items'] = undefined;






export default AchievementAggregations;

