/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Competition model module.
 * @module model/Competition
 * @version 0.0.1
 */
class Competition {
    /**
     * Constructs a new <code>Competition</code>.
     * @alias module:model/Competition
     */
    constructor() { 
        
        Competition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Competition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Competition} obj Optional instance to populate.
     * @return {module:model/Competition} The populated <code>Competition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Competition();

            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('numberOfRounds')) {
                obj['numberOfRounds'] = ApiClient.convertToType(data['numberOfRounds'], 'Number');
            }
            if (data.hasOwnProperty('actualStart')) {
                obj['actualStart'] = ApiClient.convertToType(data['actualStart'], 'Date');
            }
            if (data.hasOwnProperty('actualEnd')) {
                obj['actualEnd'] = ApiClient.convertToType(data['actualEnd'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('optinRequired')) {
                obj['optinRequired'] = ApiClient.convertToType(data['optinRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('scheduledStart')) {
                obj['scheduledStart'] = ApiClient.convertToType(data['scheduledStart'], 'Date');
            }
            if (data.hasOwnProperty('scheduledEnd')) {
                obj['scheduledEnd'] = ApiClient.convertToType(data['scheduledEnd'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('termsConditions')) {
                obj['termsConditions'] = ApiClient.convertToType(data['termsConditions'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} statusCode
 */
Competition.prototype['statusCode'] = undefined;

/**
 * @member {Number} numberOfRounds
 */
Competition.prototype['numberOfRounds'] = undefined;

/**
 * @member {Date} actualStart
 */
Competition.prototype['actualStart'] = undefined;

/**
 * @member {Date} actualEnd
 */
Competition.prototype['actualEnd'] = undefined;

/**
 * @member {String} description
 */
Competition.prototype['description'] = undefined;

/**
 * @member {Boolean} optinRequired
 */
Competition.prototype['optinRequired'] = undefined;

/**
 * @member {String} label
 */
Competition.prototype['label'] = undefined;

/**
 * @member {Date} scheduledStart
 */
Competition.prototype['scheduledStart'] = undefined;

/**
 * @member {Date} scheduledEnd
 */
Competition.prototype['scheduledEnd'] = undefined;

/**
 * @member {String} id
 */
Competition.prototype['id'] = undefined;

/**
 * @member {String} termsConditions
 */
Competition.prototype['termsConditions'] = undefined;

/**
 * @member {String} status
 */
Competition.prototype['status'] = undefined;






export default Competition;

