/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Leaderboard model module.
 * @module model/Leaderboard
 * @version 0.0.1
 */
class Leaderboard {
    /**
     * Constructs a new <code>Leaderboard</code>.
     * @alias module:model/Leaderboard
     */
    constructor() { 
        
        Leaderboard.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Leaderboard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Leaderboard} obj Optional instance to populate.
     * @return {module:model/Leaderboard} The populated <code>Leaderboard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Leaderboard();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('rank')) {
                obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
            }
            if (data.hasOwnProperty('change')) {
                obj['change'] = ApiClient.convertToType(data['change'], 'Number');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], 'Number');
            }
            if (data.hasOwnProperty('memberId')) {
                obj['memberId'] = ApiClient.convertToType(data['memberId'], 'String');
            }
            if (data.hasOwnProperty('memberRefId')) {
                obj['memberRefId'] = ApiClient.convertToType(data['memberRefId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Leaderboard.prototype['name'] = undefined;

/**
 * @member {Number} rank
 */
Leaderboard.prototype['rank'] = undefined;

/**
 * @member {Number} change
 */
Leaderboard.prototype['change'] = undefined;

/**
 * @member {Number} points
 */
Leaderboard.prototype['points'] = undefined;

/**
 * @member {String} memberId
 */
Leaderboard.prototype['memberId'] = undefined;

/**
 * @member {String} memberRefId
 */
Leaderboard.prototype['memberRefId'] = undefined;






export default Leaderboard;

