/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Error from './Error';
import MemberMessage from './MemberMessage';
import ResponseMeta from './ResponseMeta';

/**
 * The MemberMessageResponse model module.
 * @module model/MemberMessageResponse
 * @version 0.0.1
 */
class MemberMessageResponse {
    /**
     * Constructs a new <code>MemberMessageResponse</code>.
     * @alias module:model/MemberMessageResponse
     */
    constructor() { 
        
        MemberMessageResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberMessageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberMessageResponse} obj Optional instance to populate.
     * @return {module:model/MemberMessageResponse} The populated <code>MemberMessageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberMessageResponse();

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ResponseMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [MemberMessage]);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ResponseMeta} meta
 */
MemberMessageResponse.prototype['meta'] = undefined;

/**
 * @member {Array.<module:model/MemberMessage>} data
 */
MemberMessageResponse.prototype['data'] = undefined;

/**
 * @member {Array.<module:model/Error>} errors
 */
MemberMessageResponse.prototype['errors'] = undefined;






export default MemberMessageResponse;

