/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemberCompetitionAllOf model module.
 * @module model/MemberCompetitionAllOf
 * @version 0.0.1
 */
class MemberCompetitionAllOf {
    /**
     * Constructs a new <code>MemberCompetitionAllOf</code>.
     * @alias module:model/MemberCompetitionAllOf
     */
    constructor() { 
        
        MemberCompetitionAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberCompetitionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberCompetitionAllOf} obj Optional instance to populate.
     * @return {module:model/MemberCompetitionAllOf} The populated <code>MemberCompetitionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberCompetitionAllOf();

            if (data.hasOwnProperty('optin')) {
                obj['optin'] = ApiClient.convertToType(data['optin'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} optin
 */
MemberCompetitionAllOf.prototype['optin'] = undefined;






export default MemberCompetitionAllOf;

