/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemberAchievement model module.
 * @module model/MemberAchievement
 * @version 0.0.1
 */
class MemberAchievement {
    /**
     * Constructs a new <code>MemberAchievement</code>.
     * @alias module:model/MemberAchievement
     */
    constructor() { 
        
        MemberAchievement.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberAchievement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberAchievement} obj Optional instance to populate.
     * @return {module:model/MemberAchievement} The populated <code>MemberAchievement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberAchievement();

            if (data.hasOwnProperty('memberId')) {
                obj['memberId'] = ApiClient.convertToType(data['memberId'], 'String');
            }
            if (data.hasOwnProperty('achievementId')) {
                obj['achievementId'] = ApiClient.convertToType(data['achievementId'], 'String');
            }
            if (data.hasOwnProperty('goalPercentageComplete')) {
                obj['goalPercentageComplete'] = ApiClient.convertToType(data['goalPercentageComplete'], 'Number');
            }
            if (data.hasOwnProperty('issued')) {
                obj['issued'] = ApiClient.convertToType(data['issued'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} memberId
 */
MemberAchievement.prototype['memberId'] = undefined;

/**
 * @member {String} achievementId
 */
MemberAchievement.prototype['achievementId'] = undefined;

/**
 * @member {Number} goalPercentageComplete
 */
MemberAchievement.prototype['goalPercentageComplete'] = undefined;

/**
 * @member {Number} issued
 */
MemberAchievement.prototype['issued'] = undefined;






export default MemberAchievement;

