/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MainConditionSet from './MainConditionSet';

/**
 * The RuleSet model module.
 * @module model/RuleSet
 * @version 0.0.1
 */
class RuleSet {
    /**
     * Constructs a new <code>RuleSet</code>.
     * @alias module:model/RuleSet
     */
    constructor() { 
        
        RuleSet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleSet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleSet} obj Optional instance to populate.
     * @return {module:model/RuleSet} The populated <code>RuleSet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleSet();

            if (data.hasOwnProperty('jsonClass')) {
                obj['jsonClass'] = ApiClient.convertToType(data['jsonClass'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'Boolean');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('conditions')) {
                obj['conditions'] = ApiClient.convertToType(data['conditions'], [MainConditionSet]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} jsonClass
 */
RuleSet.prototype['jsonClass'] = undefined;

/**
 * @member {Number} priority
 */
RuleSet.prototype['priority'] = undefined;

/**
 * @member {Boolean} scope
 */
RuleSet.prototype['scope'] = undefined;

/**
 * @member {String} action
 */
RuleSet.prototype['action'] = undefined;

/**
 * @member {Array.<module:model/MainConditionSet>} conditions
 */
RuleSet.prototype['conditions'] = undefined;






export default RuleSet;

