/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SseMemberMessage model module.
 * @module model/SseMemberMessage
 * @version 0.0.1
 */
class SseMemberMessage {
    /**
     * Constructs a new <code>SseMemberMessage</code>.
     * @alias module:model/SseMemberMessage
     */
    constructor() { 
        
        SseMemberMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SseMemberMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SseMemberMessage} obj Optional instance to populate.
     * @return {module:model/SseMemberMessage} The populated <code>SseMemberMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SseMemberMessage();

            if (data.hasOwnProperty('nodeId')) {
                obj['nodeId'] = ApiClient.convertToType(data['nodeId'], 'String');
            }
            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
            }
            if (data.hasOwnProperty('entityId')) {
                obj['entityId'] = ApiClient.convertToType(data['entityId'], 'String');
            }
            if (data.hasOwnProperty('messageType')) {
                obj['messageType'] = ApiClient.convertToType(data['messageType'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('memberId')) {
                obj['memberId'] = ApiClient.convertToType(data['memberId'], 'String');
            }
            if (data.hasOwnProperty('parentEntityId')) {
                obj['parentEntityId'] = ApiClient.convertToType(data['parentEntityId'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('rank')) {
                obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} nodeId
 */
SseMemberMessage.prototype['nodeId'] = undefined;

/**
 * @member {String} accountId
 */
SseMemberMessage.prototype['accountId'] = undefined;

/**
 * @member {String} entityId
 */
SseMemberMessage.prototype['entityId'] = undefined;

/**
 * @member {String} messageType
 */
SseMemberMessage.prototype['messageType'] = undefined;

/**
 * @member {String} reason
 */
SseMemberMessage.prototype['reason'] = undefined;

/**
 * @member {String} memberId
 */
SseMemberMessage.prototype['memberId'] = undefined;

/**
 * @member {String} parentEntityId
 */
SseMemberMessage.prototype['parentEntityId'] = undefined;

/**
 * @member {String} subject
 */
SseMemberMessage.prototype['subject'] = undefined;

/**
 * @member {Number} rank
 */
SseMemberMessage.prototype['rank'] = undefined;






export default SseMemberMessage;

