/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubRule from './SubRule';

/**
 * The SubConditionSet model module.
 * @module model/SubConditionSet
 * @version 0.0.1
 */
class SubConditionSet {
    /**
     * Constructs a new <code>SubConditionSet</code>.
     * @alias module:model/SubConditionSet
     */
    constructor() { 
        
        SubConditionSet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubConditionSet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubConditionSet} obj Optional instance to populate.
     * @return {module:model/SubConditionSet} The populated <code>SubConditionSet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubConditionSet();

            if (data.hasOwnProperty('jsonClass')) {
                obj['jsonClass'] = ApiClient.convertToType(data['jsonClass'], 'String');
            }
            if (data.hasOwnProperty('matchCondition')) {
                obj['matchCondition'] = ApiClient.convertToType(data['matchCondition'], 'String');
            }
            if (data.hasOwnProperty('mustEvaluateTo')) {
                obj['mustEvaluateTo'] = ApiClient.convertToType(data['mustEvaluateTo'], 'Boolean');
            }
            if (data.hasOwnProperty('subRules')) {
                obj['subRules'] = ApiClient.convertToType(data['subRules'], [SubRule]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} jsonClass
 */
SubConditionSet.prototype['jsonClass'] = undefined;

/**
 * @member {String} matchCondition
 */
SubConditionSet.prototype['matchCondition'] = undefined;

/**
 * @member {Boolean} mustEvaluateTo
 */
SubConditionSet.prototype['mustEvaluateTo'] = undefined;

/**
 * @member {Array.<module:model/SubRule>} subRules
 */
SubConditionSet.prototype['subRules'] = undefined;






export default SubConditionSet;

