/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubRule model module.
 * @module model/SubRule
 * @version 0.0.1
 */
class SubRule {
    /**
     * Constructs a new <code>SubRule</code>.
     * @alias module:model/SubRule
     */
    constructor() { 
        
        SubRule.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubRule} obj Optional instance to populate.
     * @return {module:model/SubRule} The populated <code>SubRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubRule();

            if (data.hasOwnProperty('jsonClass')) {
                obj['jsonClass'] = ApiClient.convertToType(data['jsonClass'], 'String');
            }
            if (data.hasOwnProperty('fact')) {
                obj['fact'] = ApiClient.convertToType(data['fact'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('constant')) {
                obj['constant'] = ApiClient.convertToType(data['constant'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} jsonClass
 */
SubRule.prototype['jsonClass'] = undefined;

/**
 * @member {String} fact
 */
SubRule.prototype['fact'] = undefined;

/**
 * @member {String} operator
 */
SubRule.prototype['operator'] = undefined;

/**
 * @member {String} constant
 */
SubRule.prototype['constant'] = undefined;






export default SubRule;

