/*
 * Copyright (c) 2022. ZIQNI LTD registered in England and Wales, company registration number-09693684
 */

/*
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.gateway.client.api;

import com.ziqni.gateway.client.ApiException;
import com.ziqni.gateway.client.api.CompetitionsApi;
import com.ziqni.gateway.client.model.ApiErrorResponse;
import com.ziqni.gateway.client.model.CompetitionByIdResponse;
import com.ziqni.gateway.client.model.CompetitionResponse;
import com.ziqni.gateway.client.model.Error;
import org.junit.jupiter.api.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import java.util.concurrent.CompletableFuture;

/**
 * API tests for CompetitionsApi
 */
public class CompetitionsApiTest {

    private final CompetitionsApi api = new CompetitionsApi();

    
    /**
     * Returns the competition by requested id
     *
     * Returns a competition with a list of all available contests and rewards for that competition.  This assumes that a competition and contests have first been created using the web console. Otherwise, no data is returned.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompetitionByIdTest() throws ApiException {
        String X_API_KEY = null;
        String spaceName = null;
        String id = null;
        String include = null;
        String lang = null;
        String uomKey = null;
        CompletableFuture<CompetitionByIdResponse> response = 
        api.getCompetitionById(X_API_KEY, spaceName, id, include, lang, uomKey);
        
        // TODO: test validations
    }
    
    /**
     * Returns a list of competitions
     *
     * Returns a simplified list of available Competitions for ALL.  The default behaviour of a response is that the competitions that are in Ready, Active or Finished state AND are eligible for ALL will be returned unless queried otherwise.  To return eligibility for specific groups you need to send an endpoint for options limitEntrantsTo (the value of \&quot;search_word\&quot; is the member group or multiple groups that you are searching for that is eligible to participate). This filter will check eligibility against 4 types of member group setup: 1. should - if a member part of this group then a competition will be returned 2. must - the competition with this group has to exist 3. must-not - groups that can not participate 4. ALL - by default if any competition is in ALL member group then it will be returned even if the filter is request for must, should or must-not  The response is competitions that are eligible to ALL + limitEntrantsTo  This assumes that competitions have first been created using the web console otherwise no data will be returned and the value of the \&quot;totalRecordsFound\&quot; variable in metadata will be 0.  GET responses can be filtered out based on the competition parameters to narrow down the results.  The denser the queryable URL the more precise the response will be.   Sort by fields is limited to: * created (DateTime of the competition creation) * label (the label of the competition) * scheduled start and end DateTime * actual start and end DateTime * status code that indicates the status of the competition  Example:  ?_sortByFields&#x3D;created  ?_sortByFields&#x3D;label  ?_sortByFields&#x3D;options.scheduledDates.start  ?_sortByFields&#x3D;options.scheduledDates.end  ?_sortByFields&#x3D;options.actualDates.start  ?_sortByFields&#x3D;options.actualDates.end  ?_sortByFields&#x3D;statusCode
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompetitionsTest() throws ApiException {
        String X_API_KEY = null;
        String spaceName = null;
        List<String> id = null;
        Integer limit = null;
        Integer skip = null;
        String sortByFields = null;
        String include = null;
        String lang = null;
        String equal = null;
        String equalEqual = null;
        String lessThanEqual = null;
        String lessThanEqualEqual = null;
        String equalGreaterThan = null;
        String equalEqualGreaterThan = null;
        String optionsActualDatesEnd = null;
        String actualEnd = null;
        String productsProductRefId = null;
        String productRefId = null;
        String optionsProductsMetadataKey = null;
        String optionsProductsMetadataValue = null;
        String optionsProductsProductRefId = null;
        String status = null;
        Integer statusCode = null;
        List<String> optionsLimitEntrantsTo = null;
        List<String> limitEntrantsTo = null;
        String optionsScheduledDatesStart = null;
        String scheduledStart = null;
        String optionsScheduledDatesEnd = null;
        String scheduledEnd = null;
        String optionsActualDatesStart = null;
        String actualStart = null;
        CompletableFuture<CompetitionResponse> response = 
        api.getCompetitions(X_API_KEY, spaceName, id, limit, skip, sortByFields, include, lang, equal, equalEqual, lessThanEqual, lessThanEqualEqual, equalGreaterThan, equalEqualGreaterThan, optionsActualDatesEnd, actualEnd, productsProductRefId, productRefId, optionsProductsMetadataKey, optionsProductsMetadataValue, optionsProductsProductRefId, status, statusCode, optionsLimitEntrantsTo, limitEntrantsTo, optionsScheduledDatesStart, scheduledStart, optionsScheduledDatesEnd, scheduledEnd, optionsActualDatesStart, actualStart);
        
        // TODO: test validations
    }
    
}
