/*
 * Copyright (c) 2022. ZIQNI LTD registered in England and Wales, company registration number-09693684
 */

/*
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ziqni.gateway.client.api;

import com.ziqni.gateway.client.ApiException;
import com.ziqni.gateway.client.api.MembersApi;
import com.ziqni.gateway.client.model.ApiErrorResponse;
import com.ziqni.gateway.client.model.Error;
import com.ziqni.gateway.client.model.MemberResponse;
import org.junit.jupiter.api.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import java.util.concurrent.CompletableFuture;

/**
 * API tests for MembersApi
 */

public class MembersApiTest {

    private final MembersApi api = new MembersApi();

    
    /**
     * Returns the member by requested id
     *
     * Returns the information for a given Member id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMemberByIdTest() throws ApiException {
        String X_API_KEY = null;
        String spaceName = null;
        String id = null;
        CompletableFuture<MemberResponse> response = 
        api.getMemberById(X_API_KEY, spaceName, id);
        
        // TODO: test validations
    }
    
    /**
     * Returns the member by requested id
     *
     * Returns the information for a given Member Reference ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMemberByRefIdTest() throws ApiException {
        String X_API_KEY = null;
        String spaceName = null;
        String memberRefId = null;
        CompletableFuture<MemberResponse> response = 
        api.getMemberByRefId(X_API_KEY, spaceName, memberRefId);
        
        // TODO: test validations
    }
    
}
