/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@ZiqniTechGatewayApiClient);
  }
}(this, function(expect, @ZiqniTechGatewayApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @ZiqniTechGatewayApiClient.MemberMessagesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MemberMessagesApi', function() {
    describe('getMessageByIdAndMemberId', function() {
      it('should call getMessageByIdAndMemberId successfully', function(done) {
        //uncomment below and update the code to test getMessageByIdAndMemberId
        //instance.getMessageByIdAndMemberId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessageByIdAndMemberRefId', function() {
      it('should call getMessageByIdAndMemberRefId successfully', function(done) {
        //uncomment below and update the code to test getMessageByIdAndMemberRefId
        //instance.getMessageByIdAndMemberRefId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessagesByMemberId', function() {
      it('should call getMessagesByMemberId successfully', function(done) {
        //uncomment below and update the code to test getMessagesByMemberId
        //instance.getMessagesByMemberId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessagesByMemberRefId', function() {
      it('should call getMessagesByMemberRefId successfully', function(done) {
        //uncomment below and update the code to test getMessagesByMemberRefId
        //instance.getMessagesByMemberRefId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
