/**
 * Ziqni Gateway Services
 * These are the Gateway services to be used by customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@ZiqniTechGatewayApiClient);
  }
}(this, function(expect, @ZiqniTechGatewayApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @ZiqniTechGatewayApiClient.SseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SseApi', function() {
    describe('subscribeSseChannelByMemberId', function() {
      it('should call subscribeSseChannelByMemberId successfully', function(done) {
        //uncomment below and update the code to test subscribeSseChannelByMemberId
        //instance.subscribeSseChannelByMemberId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscribeSseChannelByMemberRefId', function() {
      it('should call subscribeSseChannelByMemberRefId successfully', function(done) {
        //uncomment below and update the code to test subscribeSseChannelByMemberRefId
        //instance.subscribeSseChannelByMemberRefId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscribeSseChannelHeartbeatByMemberId', function() {
      it('should call subscribeSseChannelHeartbeatByMemberId successfully', function(done) {
        //uncomment below and update the code to test subscribeSseChannelHeartbeatByMemberId
        //instance.subscribeSseChannelHeartbeatByMemberId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscribeSseChannelHeartbeatByMemberRefId', function() {
      it('should call subscribeSseChannelHeartbeatByMemberRefId successfully', function(done) {
        //uncomment below and update the code to test subscribeSseChannelHeartbeatByMemberRefId
        //instance.subscribeSseChannelHeartbeatByMemberRefId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
